version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.10
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm i
          command: npm test
workflows:
  version: 2
  test:
    jobs:
      -test
